CREATE TABLE  siase.dia 
	(ID INTEGER NOT NULL, 
	DESCRIPCION VARCHAR(25) NOT NULL, 
	 CONSTRAINT DIA_PK PRIMARY KEY (ID));
   
CREATE TABLE  siase.aula 
   (ID INTEGER NOT NULL, 
	DESCRIPCION VARCHAR(25) NOT NULL, 
	CONSTRAINT AULA_PK PRIMARY KEY (ID));
    
CREATE TABLE  siase.hora 
   (ID INTEGER NOT NULL, 
	DESCRIPCION VARCHAR(25) NOT NULL, 
	CONSTRAINT HORA_PK PRIMARY KEY (ID));
    
CREATE TABLE  siase.estatus 
   (ID INTEGER NOT NULL, 
	DESCRIPCION VARCHAR(25) NOT NULL, 
	CONSTRAINT ESTATUS_PK PRIMARY KEY (ID));
    
CREATE TABLE  siase.profesor 
   (ID INTEGER NOT NULL, 
	NOMBRE VARCHAR(50) NOT NULL, 
	ID_ESTATUS INTEGER NOT NULL, 
	CONSTRAINT PROFESOR_PK PRIMARY KEY (ID),
    FOREIGN KEY (ID_ESTATUS) REFERENCES siase.estatus(ID));

CREATE TABLE  siase.alumno 
   (ID INTEGER NOT NULL, 
	CONTRASENA VARCHAR(25) NOT NULL, 
	NOMBRE VARCHAR(50) NOT NULL, 
	CONSTRAINT ALUMNO_PK PRIMARY KEY (ID));

CREATE TABLE siase.horario 
   (ID INTEGER NOT NULL, 
	ID_HORA INTEGER NOT NULL, 
	ID_AULA INTEGER NOT NULL, 
	ID_DIA INTEGER NOT NULL, 
	ID_PROFESOR INTEGER NOT NULL, 
	CONSTRAINT HORARIO_PK PRIMARY KEY (ID),
    FOREIGN KEY (ID_HORA) REFERENCES siase.hora(ID),
    FOREIGN KEY (ID_DIA) REFERENCES siase.dia(ID),
    FOREIGN KEY (ID_AULA) REFERENCES siase.aula(ID),
    FOREIGN KEY (ID_PROFESOR) REFERENCES siase.profesores(ID));
    
CREATE TABLE  siase.materias 
   (ID INTEGER NOT NULL, 
	MATERIA VARCHAR(100) NOT NULL, 
	SEMESTRE INTEGER, 
	CONSTRAINT MATERIAS_PK PRIMARY KEY (ID));

CREATE TABLE  siase.materias_horario
   (ID INTEGER NOT NULL, 
	ID_MATERIA INTEGER NOT NULL, 
	ID_HORARIO INTEGER NOT NULL, 
	ID_ALUMNO INTEGER NOT NULL, 
	ID_ESTATUS INTEGER NOT NULL, 
	CONSTRAINT MATERIAS_HORARIO_PK PRIMARY KEY (ID),
    FOREIGN KEY (ID_ALUMNO) REFERENCES siase.alumno(ID),
	FOREIGN KEY (ID_ESTATUS) REFERENCES siase.estatus(ID),
	FOREIGN KEY (ID_HORARIO) REFERENCES siase.horario(ID),
	FOREIGN KEY (ID_MATERIA) REFERENCES siase.materias(ID));
    
CREATE TABLE  siase.facultad 
   (ID INTEGER NOT NULL, 
	NOMBRE VARCHAR(100) NOT NULL, 
	CONSTRAINT FACULTAD_PK PRIMARY KEY (ID));

CREATE TABLE  siase.carrera 
   (ID INTEGER NOT NULL, 
	NOMBRE VARCHAR(50) NOT NULL, 
	ID_FACULTAD INTEGER NOT NULL, 
	CONSTRAINT CARRERA_PK PRIMARY KEY (ID),
	FOREIGN KEY (ID_FACULTAD) REFERENCES siase.facultad(ID));

CREATE TABLE siase.plan_estudio
   (ID INTEGER, 
	FECHA_INICIO DATE NOT NULL, 
	FECHA_FIN DATE NOT NULL, 
	DESCRIPCION VARCHAR(100), 
	 CONSTRAINT PLAN_ESTUDIO_PK PRIMARY KEY (ID));
     
CREATE TABLE siase.carrera_plan_estudio
   (ID INTEGER NOT NULL, 
	ID_CARRERA INTEGER NOT NULL, 
	ID_PLAN_ESTUDIO INTEGER NOT NULL, 
	CONSTRAINT CARRERA_PLAN_ESTUDIO_PK PRIMARY KEY (ID),
	FOREIGN KEY (ID_CARRERA) REFERENCES siase.carrera(ID),
    FOREIGN KEY (ID_PLAN_ESTUDIO) REFERENCES siase.plan_estudio(ID));

CREATE TABLE siase.materia_carrera 
   (ID INTEGER NOT NULL, 
	ID_MATERIAS INTEGER NOT NULL, 
	ID_CARRERA_PLAN_ESTUDIO INTEGER NOT NULL, 
	CONSTRAINT MATERIAS_CARRERA_PK PRIMARY KEY (ID),
    FOREIGN KEY (ID_MATERIAS) REFERENCES siase.materias(ID),
    FOREIGN KEY (ID_CARRERA_PLAN_ESTUDIO) REFERENCES siase.carrera_plan_estudio(ID));
   
CREATE TABLE siase.oportunidad 
   (ID INTEGER NOT NULL, 
	DESCRIPCION VARCHAR(25) NOT NULL, 
	 CONSTRAINT OPORTUNIDAD_PK PRIMARY KEY (ID));
     
CREATE TABLE siase.calificaciones_kardex 
   (ID INTEGER NOT NULL, 
	ID_OPORTUNIDAD INTEGER NOT NULL, 
	ID_MATERIA_CARRERA INTEGER NOT NULL, 
	CALIFICACION FLOAT NOT NULL,
	ID_KARDEX INTEGER NOT NULL,
	CONSTRAINT CALIFICACIONES_KARDEX_PK PRIMARY KEY (ID),
	FOREIGN KEY (ID_MATERIA_CARRERA) REFERENCES siase.materia_carrera(ID),
	FOREIGN KEY (ID_OPORTUNIDAD) REFERENCES siase.oportunidad(ID),
	FOREIGN KEY (ID_KARDEX) REFERENCES siase.kardex(ID);
	
	ALTER TABLE siase.calificaciones_kardex 
	ADD COLUMN ID_KARDEX INT(11) NOT NULL AFTER CALIFICACION;
	
	FOREIGN KEY (ID_KARDEX) REFERENCES siase.kardex(ID);
	
    
CREATE TABLE siase.kardex
   (ID INTEGER NOT NULL, 
	FECHA_INICIO DATE NOT NULL, 
	FECHA_FIN DATE NOT NULL,
	ID_CARRERA INTEGER NOT NULL,
	CONSTRAINT KARDEX_PK PRIMARY KEY (ID),
    FOREIGN KEY (ID_CARRERA) REFERENCES siase.calificaciones_kardex(ID));
    
CREATE TABLE siase.detalle_alumno 
   (ID INTEGER NOT NULL, 
	ID_KARDEX INTEGER NOT NULL, 
	ID_ESTATUS INTEGER NOT NULL,
    ID_ALUMNO INTEGER NOT NULL,
	CONSTRAINT DETALLE_ALUMNO_PK PRIMARY KEY (ID),
	FOREIGN KEY (ID_ESTATUS) REFERENCES siase.estatus(ID),
	FOREIGN KEY (ID_KARDEX) REFERENCES siase.kardex(ID),
    FOREIGN KEY (ID_ALUMNO) REFERENCES siase.alumno(ID));
    
CREATE TABLE siase.materias_horario_alumno
	(ID INTEGER NOT NULL,
	ID_MATERIAS_HORARIO INTEGER NOT NULL,
	ID_ALUMNO INTEGER NOT NULL,
	CONSTRAINT MATERIAS_HORARIOS_ALUMNO_PK PRIMARY KEY (ID),
	FOREIGN KEY (ID_ALUMNO) REFERENCES siase.alumno(ID),
	FOREIGN KEY (ID_MATERIAS_HORARIO) REFERENCES siase.(ID);