CREATE TABLE  login.dia 
	(ID INTEGER NOT NULL, 
	DESCRIPCION VARCHAR(25) NOT NULL, 
	 CONSTRAINT DIA_PK PRIMARY KEY (ID));
   
CREATE TABLE  login.aula 
   (ID INTEGER NOT NULL, 
	DESCRIPCION VARCHAR(25) NOT NULL, 
	CONSTRAINT AULA_PK PRIMARY KEY (ID));
    
CREATE TABLE  login.hora 
   (ID INTEGER NOT NULL, 
	DESCRIPCION VARCHAR(25) NOT NULL, 
	CONSTRAINT HORA_PK PRIMARY KEY (ID));
    
CREATE TABLE  login.estatus 
   (ID INTEGER NOT NULL, 
	DESCRIPCION VARCHAR(25) NOT NULL, 
	CONSTRAINT ESTATUS_PK PRIMARY KEY (ID));
    
CREATE TABLE  login.profesores 
   (ID INTEGER NOT NULL, 
	NOMBRE VARCHAR(50) NOT NULL, 
	ID_ESTATUS INTEGER NOT NULL, 
	CONSTRAINT PROFESOR_PK PRIMARY KEY (ID),
    FOREIGN KEY (ID_ESTATUS) REFERENCES login.estatus(ID));

CREATE TABLE  login.alumno 
   (ID INTEGER NOT NULL, 
	CONTRASENA VARCHAR(25) NOT NULL, 
	NOMBRE VARCHAR(50) NOT NULL, 
	CONSTRAINT ALUMNO_PK PRIMARY KEY (ID));

CREATE TABLE login.horario 
   (ID INTEGER NOT NULL, 
	ID_HORA INTEGER NOT NULL, 
	ID_AULA INTEGER NOT NULL, 
	ID_DIA INTEGER NOT NULL, 
	ID_PROFESOR INTEGER NOT NULL, 
	CONSTRAINT HORARIO_PK PRIMARY KEY (ID),
    FOREIGN KEY (ID_HORA) REFERENCES login.hora(ID),
    FOREIGN KEY (ID_DIA) REFERENCES login.dia(ID),
    FOREIGN KEY (ID_AULA) REFERENCES login.aula(ID),
    FOREIGN KEY (ID_PROFESOR) REFERENCES login.profesores(ID));
    
CREATE TABLE  login.materias 
   (ID INTEGER NOT NULL, 
	MATERIA VARCHAR(100) NOT NULL, 
	SEMESTRE INTEGER, 
	CONSTRAINT MATERIAS_PK PRIMARY KEY (ID));

CREATE TABLE  login.materias_horario
   (ID INTEGER NOT NULL, 
	ID_MATERIA INTEGER NOT NULL, 
	ID_HORARIO INTEGER NOT NULL, 
	ID_ALUMNO INTEGER NOT NULL, 
	ID_ESTATUS INTEGER NOT NULL, 
	CONSTRAINT MATERIAS_HORARIO_PK PRIMARY KEY (ID),
    FOREIGN KEY (ID_ALUMNO) REFERENCES login.alumno(ID),
	FOREIGN KEY (ID_ESTATUS) REFERENCES login.estatus(ID),
	FOREIGN KEY (ID_HORARIO) REFERENCES login.horario(ID),
	FOREIGN KEY (ID_MATERIA) REFERENCES login.materias(ID));
    
CREATE TABLE  login.facultad 
   (ID INTEGER NOT NULL, 
	NOMBRE VARCHAR(100) NOT NULL, 
	CONSTRAINT FACULTAD_PK PRIMARY KEY (ID));

CREATE TABLE  login.carrera 
   (ID INTEGER NOT NULL, 
	NOMBRE VARCHAR(50) NOT NULL, 
	ID_FACULTAD INTEGER NOT NULL, 
	CONSTRAINT CARRERA_PK PRIMARY KEY (ID),
	FOREIGN KEY (ID_FACULTAD) REFERENCES login.materias(ID));

CREATE TABLE  login.plan_estudio
   (ID INTEGER, 
	FECHA_INICIO DATE NOT NULL, 
	FECHA_FIN DATE NOT NULL, 
	DESCRIPCION VARCHAR(100), 
	 CONSTRAINT PLAN_ESTUDIO_PK PRIMARY KEY (ID));
     
CREATE TABLE  login.carrera_plan_estudio
   (ID INTEGER NOT NULL, 
	ID_CARRERA INTEGER NOT NULL, 
	ID_PLAN_ESTUDIO INTEGER NOT NULL, 
	CONSTRAINT CARRERA_PLAN_ESTUDIO_PK PRIMARY KEY (ID),
	FOREIGN KEY (ID_CARRERA) REFERENCES login.carrera(ID),
    FOREIGN KEY (ID_PLAN_ESTUDIO) REFERENCES login.plan_estudio(ID));

CREATE TABLE login.materia_carrera 
   (ID INTEGER NOT NULL, 
	ID_MATERIAS INTEGER NOT NULL, 
	ID_CARRERA_PLAN_ESTUDIO INTEGER NOT NULL, 
	CONSTRAINT MATERIAS_CARRERA_PK PRIMARY KEY (ID),
    FOREIGN KEY (ID_MATERIAS) REFERENCES login.materias(ID),
    FOREIGN KEY (ID_CARRERA_PLAN_ESTUDIO) REFERENCES login.carrera_plan_estudio(ID));
   
CREATE TABLE login.oportunidad 
   (ID INTEGER NOT NULL, 
	DESCRIPCION VARCHAR(25) NOT NULL, 
	 CONSTRAINT OPORTUNIDAD_PK PRIMARY KEY (ID));
     
CREATE TABLE login.calificaciones_kardex 
   (ID INTEGER NOT NULL, 
	ID_OPORTUNIDAD INTEGER NOT NULL, 
	ID_MATERIA_CARRERA INTEGER NOT NULL, 
	CALIFICACION FLOAT NOT NULL, 
	CONSTRAINT CALIFICACIONES_KARDEX_PK PRIMARY KEY (ID),
	FOREIGN KEY (ID_MATERIA_CARRERA) REFERENCES login.materia_carrera(ID),
	FOREIGN KEY (ID_OPORTUNIDAD) REFERENCES login.oportunidad(ID));
    
CREATE TABLE login.kardex
   (ID INTEGER NOT NULL, 
	MATRÍCULA_ALUMNO INTEGER NOT NULL, 
	ID_CALIFICACION_KARDEX INTEGER NOT NULL, 
	CONSTRAINT KARDEX_PK PRIMARY KEY (ID),
    FOREIGN KEY (ID_CALIFICACION_KARDEX) REFERENCES login.calificaciones_kardex(ID));
    
CREATE TABLE login.detalle_alumno 
   (ID INTEGER NOT NULL, 
	ID_KARDEX INTEGER NOT NULL, 
	ID_ESTATUS INTEGER NOT NULL,
    ID_ALUMNO INTEGER NOT NULL,
	CONSTRAINT DETALLE_ALUMNO_PK PRIMARY KEY (ID),
	FOREIGN KEY (ID_ESTATUS) REFERENCES login.estatus(ID),
	FOREIGN KEY (ID_KARDEX) REFERENCES login.kardex(ID),
    FOREIGN KEY (ID_ALUMNO) REFERENCES login.alumno(ID));
    
